# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 806)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(117, 12, 26);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(151, 10, 16);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_toggle)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_loggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_loggle.sizePolicy().hasHeightForWidth())
        self.Btn_loggle.setSizePolicy(sizePolicy)
        self.Btn_loggle.setStyleSheet("QPushButton {    \n"
"background-image: url(:/20x20/icons/20x20/cil-menu.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"\n"
"}\n"
"")
        self.Btn_loggle.setText("")
        self.Btn_loggle.setObjectName("Btn_loggle")
        self.horizontalLayout_3.addWidget(self.Btn_loggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_8.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(self.frame_top)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.horizontalLayout.addWidget(self.frame_top)
        self.frame = QtWidgets.QFrame(self.Top_Bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(180, 90))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_6.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-image: url(:/16x16/icons/16x16/cil-window-minimize.png);\n"
"    background-position: top center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(151, 10, 16);\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_5.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-image: url(:/16x16/icons/16x16/cil-window-restore.png);\n"
"    background-position:center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(151, 10, 16);\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_4.setStyleSheet("QPushButton {    \n"
"    \n"
"    background-image: url(:/16x16/icons/16x16/cil-x.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(151, 10, 16);\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_4.addWidget(self.pushButton_4)
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(151, 10, 16);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top_menu = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menu.setObjectName("frame_top_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_top_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_top_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_1.sizePolicy().hasHeightForWidth())
        self.pushButton_1.setSizePolicy(sizePolicy)
        self.pushButton_1.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.pushButton_1.setFont(font)
        self.pushButton_1.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-image: url(:/20x20/icons/20x20/cil-home.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid  rgb(151, 10, 16);\n"
"    background-color:  rgb(151, 10, 16);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    border-left: 28px solid rgb(117, 12, 26);\n"
"}\n"
"")
        self.pushButton_1.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_1.setObjectName("pushButton_1")
        self.verticalLayout_3.addWidget(self.pushButton_1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_top_menu)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_7.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    background-image: url(:/20x20/icons/20x20/cil-user.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid  rgb(151, 10, 16);\n"
"    background-color:  rgb(151, 10, 16);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    border-left: 28px solid rgb(117, 12, 26);\n"
"}\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_3.addWidget(self.pushButton_7)
        self.pushButton = QtWidgets.QPushButton(self.frame_top_menu)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-image: url(:/20x20/icons/20x20/cil-user-follow.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid  rgb(151, 10, 16);\n"
"    background-color:  rgb(151, 10, 16);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    border-left: 28px solid rgb(117, 12, 26);\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_3.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_top_menu)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-image: url(:/20x20/icons/20x20/cil-settings.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid  rgb(151, 10, 16);\n"
"    background-color:  rgb(151, 10, 16);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    border-left: 28px solid rgb(117, 12, 26);\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_top_menu)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setStyleSheet("QPushButton {    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    background-image: url(:/16x16/icons/16x16/cil-account-logout.png);\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 28px solid  rgb(151, 10, 16);\n"
"    background-color:  rgb(151, 10, 16);\n"
"    text-align: left;\n"
"    padding-left: 45px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    border-left: 28px solid rgb(117, 12, 26);\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_3.addWidget(self.pushButton_3)
        self.verticalLayout_2.addWidget(self.frame_top_menu, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Pages = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages.setMinimumSize(QtCore.QSize(70, 0))
        self.Pages.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Pages.setObjectName("Pages")
        self.PagesPage1_2 = QtWidgets.QWidget()
        self.PagesPage1_2.setObjectName("PagesPage1_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.PagesPage1_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.PagesPage1_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet("background-color: #CBC3BE;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.image_label = QtWidgets.QLabel(self.frame_2)
        self.image_label.setStyleSheet("background-color: #CBC3BE;\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_5.addWidget(self.image_label)
        self.control_bt = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_bt.sizePolicy().hasHeightForWidth())
        self.control_bt.setSizePolicy(sizePolicy)
        self.control_bt.setMinimumSize(QtCore.QSize(200, 35))
        self.control_bt.setMaximumSize(QtCore.QSize(500, 16777215))
        self.control_bt.setSizeIncrement(QtCore.QSize(0, 0))
        self.control_bt.setBaseSize(QtCore.QSize(0, 0))
        self.control_bt.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.control_bt.setAutoRepeatInterval(100)
        self.control_bt.setObjectName("control_bt")
        self.verticalLayout_5.addWidget(self.control_bt, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.PagesPage1_2)
        self.frame_3.setStyleSheet("background-color: #CBC3BE;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.image_label_2 = QtWidgets.QLabel(self.frame_3)
        self.image_label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.image_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label_2.setObjectName("image_label_2")
        self.verticalLayout_7.addWidget(self.image_label_2)
        self.control_bt_2 = QtWidgets.QPushButton(self.frame_3)
        self.control_bt_2.setMinimumSize(QtCore.QSize(200, 35))
        self.control_bt_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.control_bt_2.setObjectName("control_bt_2")
        self.verticalLayout_7.addWidget(self.control_bt_2, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addWidget(self.frame_3)
        self.Pages.addWidget(self.PagesPage1_2)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_13 = QtWidgets.QFrame(self.page)
        self.frame_13.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_14 = QtWidgets.QFrame(self.frame_13)
        self.frame_14.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_14.setStyleSheet("")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_14.setContentsMargins(0, 0, -1, 0)
        self.verticalLayout_14.setSpacing(11)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_16.setStyleSheet("")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_22 = QtWidgets.QFrame(self.frame_16)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_22.setStyleSheet("background-color: rgb(23, 38, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.frame_22)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_11.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.verticalLayout_15.addWidget(self.frame_22)
        self.frame_21 = QtWidgets.QFrame(self.frame_16)
        self.frame_21.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_21)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 30))
        self.lineEdit_3.setStyleSheet("font: 75 9pt \"MS Shell Dlg 2\";")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_16.addWidget(self.lineEdit_3)
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_9.setMaximumSize(QtCore.QSize(5000, 35))
        self.pushButton_9.setSizeIncrement(QtCore.QSize(3, 0))
        self.pushButton_9.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_9.setStyleSheet("QPushButton {    \n"
"background-image: url(:/16x16/icons/16x16/cil-magnifying-glass.png);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-color: rgb(84, 95, 255);    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"\n"
"}\n"
"")
        self.pushButton_9.setText("")
        self.pushButton_9.setIconSize(QtCore.QSize(20, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_16.addWidget(self.pushButton_9, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_21)
        self.verticalLayout_14.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_14)
        self.frame_17.setStyleSheet("")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_23 = QtWidgets.QFrame(self.frame_17)
        self.frame_23.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_23.setStyleSheet("background-color: rgb(23, 38, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_13 = QtWidgets.QLabel(self.frame_23)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_13.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_18.addWidget(self.label_13)
        self.verticalLayout_20.addWidget(self.frame_23)
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_18)
        self.dateTimeEdit.setGeometry(QtCore.QRect(20, 90, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.frame_18)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(20, 130, 194, 22))
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.verticalLayout_20.addWidget(self.frame_18)
        self.verticalLayout_14.addWidget(self.frame_17)
        self.horizontalLayout_10.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_13)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_10.addWidget(self.frame_15)
        self.verticalLayout_13.addWidget(self.frame_13)
        self.Pages.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_26 = QtWidgets.QFrame(self.page_2)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_35 = QtWidgets.QFrame(self.frame_26)
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_35.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";background-color: rgba(204, 111, 101);\n"
"color: rgb(255, 255, 255);    border-radius: 10px;")
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_12 = QtWidgets.QLabel(self.frame_35)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_22.addWidget(self.label_12)
        self.verticalLayout_21.addWidget(self.frame_35)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setStyleSheet("background-color: rgb(198, 198, 198);")
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_28)
        self.gridLayout_4.setContentsMargins(11, -1, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_38 = QtWidgets.QFrame(self.frame_28)
        self.frame_38.setMaximumSize(QtCore.QSize(640, 300))
        self.frame_38.setStyleSheet("")
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_23.setSpacing(0)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_39 = QtWidgets.QFrame(self.frame_38)
        self.frame_39.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_39.setStyleSheet("background-color: rgb(23, 38, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.label_29 = QtWidgets.QLabel(self.frame_39)
        self.label_29.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.verticalLayout_24.addWidget(self.label_29)
        self.verticalLayout_23.addWidget(self.frame_39)
        self.frame_24 = QtWidgets.QFrame(self.frame_38)
        self.frame_24.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_24)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_31 = QtWidgets.QLabel(self.frame_24)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 1, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.frame_24)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 0, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.frame_24)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 2, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_24)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_4, 0, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.frame_24)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.frame_24)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_6, 2, 1, 1, 1)
        self.verticalLayout_23.addWidget(self.frame_24)
        self.gridLayout_4.addWidget(self.frame_38, 0, 0, 1, 1)
        self.frame_37 = QtWidgets.QFrame(self.frame_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_37.sizePolicy().hasHeightForWidth())
        self.frame_37.setSizePolicy(sizePolicy)
        self.frame_37.setMaximumSize(QtCore.QSize(640, 16777215))
        self.frame_37.setStyleSheet("")
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_40 = QtWidgets.QFrame(self.frame_37)
        self.frame_40.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_40.setStyleSheet("background-color: rgb(23, 38, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.label_33 = QtWidgets.QLabel(self.frame_40)
        self.label_33.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_33.setObjectName("label_33")
        self.verticalLayout_25.addWidget(self.label_33)
        self.verticalLayout_26.addWidget(self.frame_40)
        self.frame_25 = QtWidgets.QFrame(self.frame_37)
        self.frame_25.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_6.addWidget(self.lineEdit_9, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_6.addWidget(self.lineEdit_10, 1, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.frame_25)
        self.label_35.setObjectName("label_35")
        self.gridLayout_6.addWidget(self.label_35, 1, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.frame_25)
        self.label_36.setObjectName("label_36")
        self.gridLayout_6.addWidget(self.label_36, 2, 0, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_14.setMinimumSize(QtCore.QSize(70, 35))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_6.addWidget(self.pushButton_14, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.frame_25)
        self.label_34.setObjectName("label_34")
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_25)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_6.addWidget(self.lineEdit_11, 2, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_15.setMinimumSize(QtCore.QSize(70, 35))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_6.addWidget(self.pushButton_15, 2, 2, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_25)
        self.pushButton_8.setMinimumSize(QtCore.QSize(70, 35))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_6.addWidget(self.pushButton_8, 0, 2, 1, 1)
        self.verticalLayout_26.addWidget(self.frame_25)
        self.gridLayout_4.addWidget(self.frame_37, 0, 1, 1, 1)
        self.frame_36 = QtWidgets.QFrame(self.frame_28)
        self.frame_36.setStyleSheet("")
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_41 = QtWidgets.QFrame(self.frame_36)
        self.frame_41.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_41.setStyleSheet("background-color: rgb(23, 38, 255);\n"
"color: rgb(255, 255, 255);")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_37 = QtWidgets.QLabel(self.frame_41)
        self.label_37.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_37.setObjectName("label_37")
        self.verticalLayout_27.addWidget(self.label_37)
        self.verticalLayout_28.addWidget(self.frame_41)
        self.frame_27 = QtWidgets.QFrame(self.frame_36)
        self.frame_27.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.comboBox_7 = QtWidgets.QComboBox(self.frame_27)
        self.comboBox_7.setGeometry(QtCore.QRect(70, 80, 181, 41))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.verticalLayout_28.addWidget(self.frame_27)
        self.gridLayout_4.addWidget(self.frame_36, 0, 2, 1, 1)
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_4.addWidget(self.frame_29, 1, 0, 1, 1)
        self.verticalLayout_21.addWidget(self.frame_28)
        self.horizontalLayout_12.addWidget(self.frame_26)
        self.Pages.addWidget(self.page_2)
        self.PagesPage2_2 = QtWidgets.QWidget()
        self.PagesPage2_2.setObjectName("PagesPage2_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.PagesPage2_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.PagesPage2_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMaximumSize(QtCore.QSize(16777215, 35))
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";background-color: rgba(204, 111, 101);\n"
"color: rgb(255, 255, 255);    border-radius: 10px;")
        self.label.setObjectName("label")
        self.verticalLayout_10.addWidget(self.label)
        self.verticalLayout_9.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setStyleSheet("background-color: rgb(253, 253, 253);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout.setContentsMargins(100, -1, 100, -1)
        self.gridLayout.setSpacing(14)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_6)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.frame_10)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_10 = QtWidgets.QLabel(self.frame_9)
        self.label_10.setStyleSheet("background-color: rgb(245, 245, 245);    border-radius: 10px;")
        self.label_10.setText("")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_12.addWidget(self.label_10)
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.frame_12 = QtWidgets.QFrame(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_12.sizePolicy().hasHeightForWidth())
        self.frame_12.setSizePolicy(sizePolicy)
        self.frame_12.setStyleSheet("")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_20 = QtWidgets.QFrame(self.frame_12)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 120))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(14)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_11.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_11.addWidget(self.pushButton_11)
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_13.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_11.addWidget(self.pushButton_13)
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_12.setMaximumSize(QtCore.QSize(16777215, 40))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_11.addWidget(self.pushButton_12)
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_20)
        self.pushButton_10.setMaximumSize(QtCore.QSize(150, 40))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    background-color: rgb(220, 220, 220);\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:rgb(117, 12, 26);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_11.addWidget(self.pushButton_10)
        self.verticalLayout_19.addWidget(self.frame_20)
        self.frame_19 = QtWidgets.QFrame(self.frame_12)
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_20 = QtWidgets.QLabel(self.frame_19)
        self.label_20.setText("")
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.frame_19)
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 0, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.frame_19)
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.frame_19)
        self.label_23.setText("")
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.frame_19)
        self.label_24.setText("")
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.frame_19)
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.gridLayout_3.addWidget(self.label_25, 1, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.frame_19)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.frame_19)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 2, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.frame_19)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 2, 2, 1, 1)
        self.verticalLayout_19.addWidget(self.frame_19)
        self.horizontalLayout_9.addWidget(self.frame_12)
        self.gridLayout.addWidget(self.frame_10, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(15)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_8.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_8.setStyleSheet("image: url(:/16x16/icons/depositphotos_318221368-stock-illustration-missing-picture-page-for-website.jpg);\n"
"background-position:  center;\n"
"background-repeat: no-repeat;    border-radius: 10px;\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_8 = QtWidgets.QLabel(self.frame_8)
        self.label_8.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_8.setText("")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_11.addWidget(self.label_8)
        self.horizontalLayout_7.addWidget(self.frame_8)
        self.frame_11 = QtWidgets.QFrame(self.frame_7)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 250))
        self.frame_11.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgba(250, 250, 250, 250);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMaximumSize(QtCore.QSize(250, 50))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 1, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_11)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_11)
        self.label_2.setMaximumSize(QtCore.QSize(150, 30))
        self.label_2.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(150, 500))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 5, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setMaximumSize(QtCore.QSize(150, 30))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMaximumSize(QtCore.QSize(250, 16777215))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setMaximumSize(QtCore.QSize(150, 30))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMaximumSize(QtCore.QSize(250, 50))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 3, 6, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.frame_11)
        self.dateEdit.setMaximumSize(QtCore.QSize(250, 50))
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_2.addWidget(self.dateEdit, 3, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 5, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        self.label_15.setMaximumSize(QtCore.QSize(150, 30))
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 0, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 2, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 2, 1, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_5.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_2.addWidget(self.lineEdit_5, 0, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 2, 5, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_2.addWidget(self.lineEdit_6, 2, 6, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        self.label_17.setMaximumSize(QtCore.QSize(150, 30))
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 2, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_7.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_2.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.frame_11)
        self.label_18.setMaximumSize(QtCore.QSize(150, 30))
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 2, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(250, 50))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_2.addWidget(self.lineEdit_8, 2, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.frame_11)
        self.label_19.setMaximumSize(QtCore.QSize(150, 30))
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 2, 1, 1)
        self.dateEdit_2 = QtWidgets.QDateEdit(self.frame_11)
        self.dateEdit_2.setMaximumSize(QtCore.QSize(250, 50))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_2.addWidget(self.dateEdit_2, 3, 3, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.gridLayout.addWidget(self.frame_7, 0, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.Pages.addWidget(self.PagesPage2_2)
        self.verticalLayout_4.addWidget(self.Pages)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_9.setText(_translate("MainWindow", "FaKeep"))
        self.pushButton_1.setText(_translate("MainWindow", "Home"))
        self.pushButton_7.setText(_translate("MainWindow", "Quản lý "))
        self.pushButton.setText(_translate("MainWindow", "Tạo mới "))
        self.pushButton_2.setText(_translate("MainWindow", "Cài đặt"))
        self.pushButton_3.setText(_translate("MainWindow", "Đăng xuất"))
        self.image_label.setText(_translate("MainWindow", "Open camera"))
        self.control_bt.setText(_translate("MainWindow", "CHECK IN"))
        self.image_label_2.setText(_translate("MainWindow", "Open camera"))
        self.control_bt_2.setText(_translate("MainWindow", "CHECK OUT"))
        self.label_11.setText(_translate("MainWindow", " Tìm kiếm"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", " Nhập nội dung tìm kiếm"))
        self.label_13.setText(_translate("MainWindow", " Bộ lọc"))
        self.label_12.setText(_translate("MainWindow", " Cài đặt"))
        self.label_29.setText(_translate("MainWindow", "Camera"))
        self.label_31.setText(_translate("MainWindow", "Camera check out"))
        self.label_30.setText(_translate("MainWindow", "Camera check in"))
        self.label_32.setText(_translate("MainWindow", "Camera chụp ảnh"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "IP"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "IP1"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "IP"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "IP1"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "0"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "IP"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "IP1"))
        self.label_33.setText(_translate("MainWindow", "Tải dữ liệu"))
        self.label_35.setText(_translate("MainWindow", "Data User"))
        self.label_36.setText(_translate("MainWindow", "Data Admin"))
        self.pushButton_14.setText(_translate("MainWindow", "Browse"))
        self.label_34.setText(_translate("MainWindow", "Data Staff"))
        self.pushButton_15.setText(_translate("MainWindow", "Browse"))
        self.pushButton_8.setText(_translate("MainWindow", "Browse"))
        self.label_37.setText(_translate("MainWindow", "Màu sắc"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "Giao diện load"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "Giao diện login"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "Thanh ngang"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", "Thanh dọc"))
        self.comboBox_7.setItemText(4, _translate("MainWindow", "Nền"))
        self.label.setText(_translate("MainWindow", "  Đăng ký thông tin nhân viên"))
        self.pushButton_11.setText(_translate("MainWindow", "Chụp ảnh"))
        self.pushButton_13.setText(_translate("MainWindow", "Xem"))
        self.pushButton_12.setText(_translate("MainWindow", "Mở file ảnh"))
        self.pushButton_10.setText(_translate("MainWindow", "Thêm"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Giám đốc"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Trường phòng"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Phó phòng"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Nhân viên"))
        self.label_5.setText(_translate("MainWindow", "Chức danh"))
        self.label_2.setText(_translate("MainWindow", "Mã nhân viên"))
        self.label_4.setText(_translate("MainWindow", "Phòng ban"))
        self.label_3.setText(_translate("MainWindow", "Tên nhân viên"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Kế toán"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Nhân sự"))
        self.label_6.setText(_translate("MainWindow", "Ngày sinh"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Nam"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Nữ"))
        self.label_7.setText(_translate("MainWindow", "Giới tính"))
        self.label_15.setText(_translate("MainWindow", "Email"))
        self.label_14.setText(_translate("MainWindow", "Số điện thoại"))
        self.label_16.setText(_translate("MainWindow", "Mức lương"))
        self.label_17.setText(_translate("MainWindow", "Địa chỉ"))
        self.label_18.setText(_translate("MainWindow", "CMND/CCCD"))
        self.label_19.setText(_translate("MainWindow", "Ngày vào làm"))
import files_rc
